import { initializeApp } from 'firebase/app';
import { getFirestore, collection, getDocs, deleteDoc, doc } from 'firebase/firestore';

const firebaseConfig = {
    apiKey: 'AIzaSyCT5NbWoisuNzpIAaPcK8dNOpCF9lPx31I',
    projectId: 'theseeksacademy-66d12',
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

async function cleanup() {
    console.log('Fetching all exams...');
    const snap = await getDocs(collection(db, 'exams'));
    
    // We filter out duplicates based on rollNo length.
    // Dashboard (Admin panel) uses Firebase Document IDs (20 chars) for rollNo in exams.
    // The duplicated ones created by the Teacher app bug have short roll numbers (like '208', '38').
    const duplicates = snap.docs.filter(d => {
        const data = d.data();
        const rollNo = data.rollNo ? String(data.rollNo).trim() : '';
        // Only delete if it's a short roll number AND it was created today (July 23, 2026).
        // Since we don't have created_at reliable, we know any ID generated by Date.now() today starts with '178342'
        // And any doc ID generated by Teacher app today would have been created with the old short roll number bug.
        // Wait, any short roll number in `exams` is a bug from the Teacher App because legitimate exams from Dashboard use Firebase IDs.
        // Are there ANY legitimate exams with short roll numbers? Let's check all of them.
        return rollNo.length > 0 && rollNo.length < 15;
    });

    console.log(`Found ${duplicates.length} duplicate/invalid records remaining.`);
    
    // Let's just list them without deleting for now
    for (const d of duplicates) {
        const data = d.data();
        console.log(`ID: ${d.id} | Name: ${data.studentName} | Class: ${data.studentClass} | RollNo: ${data.rollNo}`);
    }
    
    process.exit(0);
}

cleanup().catch(err => {
    console.error('Error during cleanup:', err);
    process.exit(1);
});
